# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "algo_tests" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - uses: nelonoel/branch-name@v1.0.1
    - name: Deploy coverage report
      uses: jsmrcaga/action-netlify-deploy@master
      with:
        NETLIFY_AUTH_TOKEN: nfp_D5vL9v492PdjYhMACDZsz364HLtK5oXD64d9
        NETLIFY_SITE_ID: a44c5e7d-7f60-44b7-b756-b921b9754aa9
        build_directory: aggregate-report/target/site/jacoco-aggregate
        build_command: echo "Deploying..."
        deploy_alias: ${{ env.BRANCH_NAME }}
    - name: Status check
      uses: Sibz/github-status-action@v1.1.1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Netlify preview
        state: success
        target_url: ${{ env.NETLIFY_PREVIEW_URL }}
    - name: jacoco-reporter
      uses: PavanMudigonda/jacoco-reporter@v4.9
      with:
        coverage_results_path: aggregate-report/target/site/jacoco-aggregate/jacoco.xml
        coverage_report_name: Coverage
        coverage_report_title: Coverate report
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 90
        fail_below_threshold: true
        publish_only_summary: true